[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "stdenv.cc.cc.lib"]

[phases.install]
cmds = ["pip install --break-system-packages -r server/requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python3 -m uvicorn server.main:app --host 0.0.0.0 --port $PORT"
